apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscalevote
  namespace: prod
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voteapp
  targetCPUUtilizationPercentage: 70